import type { MissionDefinition } from "@/types/mission";

const r = String.raw;

export const BF_001: MissionDefinition = {
  id: "BF-001",
  companyId: "byteforge",
  level: 1,
  title: "Deploy a Student Portal",
  client: "Riverside Community College",
  difficulty: "Beginner",
  priority: "Medium",
  estimatedTime: "30–45 minutes",
  deadline: "End of sprint · 45 min",
  brief: [
    "ByteForge Solutions has signed a small contract with Riverside Community College. They need a simple student portal running on a Linux server.",
    "The previous intern left the server half-configured and nobody documented anything. Build a clean, working LAMP environment from scratch and deliver a PHP page that lists students from a MySQL/MariaDB database through Apache.",
  ],
  objectives: [
    "Prepare the Linux environment (update packages).",
    "Install and start Apache.",
    "Install PHP and the PHP MySQL extension.",
    "Install and start MySQL or MariaDB.",
    "Create a database for the portal (e.g. student_portal).",
    "Create a `students` table with the columns: id, name, email, course.",
    "Create a PHP page (e.g. index.php).",
    "Connect the PHP page to the database (mysqli or PDO).",
    "Query the students table and display each student on the page.",
    "Serve the page through Apache (e.g. /var/www/html) and verify it in a browser or with curl.",
  ],
  constraints: [
    "Use Apache as the web server (no PHP built-in server for the final result).",
    "Do not connect to the database as the MySQL root user — create an application user.",
    "Keep each piece in its own file: shell commands, SQL, PHP.",
    "Do not include binaries, vendor folders or database dumps larger than a few KB.",
  ],
  expectedOutput: [
    "A single .zip containing: setup.sh (or commands.txt) with every command you ran, schema.sql with the database and table, index.php (or similar) and optionally your Apache config.",
    "A single .txt / .md / .pdf / .docx report containing the same commands, SQL and PHP code is also accepted.",
    "Max file size: 4 MB.",
  ],
  hints: [
    "On Ubuntu/Debian: `sudo apt update && sudo apt install apache2 php libapache2-mod-php php-mysql mariadb-server`.",
    "Create the table with something like: `CREATE TABLE students (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100), email VARCHAR(150), course VARCHAR(100));`",
    "In PHP: `$db = new mysqli('localhost', 'portal_user', 'secret', 'student_portal');` then `$result = $db->query('SELECT * FROM students');` and loop with `fetch_assoc()`.",
  ],
  submission: {
    allowedExtensions: [".zip", ".txt", ".md", ".pdf", ".docx", ".php", ".sql", ".sh", ".conf"],
    maxSizeMB: 4,
  },
  passThreshold: 70,
  requirements: [
    {
      id: "linux-setup",
      label: "Linux environment prepared",
      level: 4,
      weight: 10,
      tags: ["linux"],
      rule: {
        kind: "commands",
        mode: "any",
        commands: [r`\bapt(-get)?\s+(update|upgrade)\b`, r`\b(dnf|yum)\s+(update|upgrade|check-update)\b`],
      },
      failFeedback: "No package update command found — the Linux environment preparation is not documented.",
      suggestion: "Include the command you used to update the system, e.g. `sudo apt update`.",
    },
    {
      id: "apache-installed",
      label: "Apache installed and running",
      level: 4,
      weight: 10,
      critical: true,
      tags: ["apache"],
      rule: {
        kind: "commands",
        mode: "any",
        commands: [
          r`\b(apt(-get)?|dnf|yum)\s+install\b[^\n]*\b(apache2|httpd)\b`,
          r`\bsystemctl\s+(start|enable|restart|status)\s+(apache2|httpd)\b`,
          r`\bservice\s+(apache2|httpd)\s+(start|restart)\b`,
        ],
      },
      failFeedback: "Apache installation/start commands were not found.",
      suggestion: "Add `sudo apt install apache2` and `sudo systemctl enable --now apache2` to your commands.",
    },
    {
      id: "php-installed",
      label: "PHP installed",
      level: 4,
      weight: 10,
      tags: ["php"],
      rule: {
        kind: "commands",
        mode: "any",
        commands: [
          r`\b(apt(-get)?|dnf|yum)\s+install\b[^\n]*\bphp(\d+(\.\d+)?)?\b`,
          r`\blibapache2-mod-php\b`,
          r`\bphp(\d+(\.\d+)?)?-mysql(nd)?\b`,
        ],
      },
      failFeedback: "PHP installation was not detected.",
      suggestion: "Install PHP with the Apache module and MySQL extension: `sudo apt install php libapache2-mod-php php-mysql`.",
    },
    {
      id: "database-installed",
      label: "MySQL / MariaDB installed",
      level: 4,
      weight: 10,
      tags: ["mysql"],
      rule: {
        kind: "commands",
        mode: "any",
        commands: [
          r`\b(apt(-get)?|dnf|yum)\s+install\b[^\n]*\b(mysql-server|mariadb-server|mariadb)\b`,
          r`\bsystemctl\s+(start|enable|restart|status)\s+(mysql|mysqld|mariadb)\b`,
        ],
      },
      failFeedback: "No MySQL/MariaDB installation or service command found.",
      suggestion: "Add `sudo apt install mariadb-server` (or mysql-server) and start the service.",
    },
    {
      id: "database-created",
      label: "Database created",
      level: 3,
      weight: 10,
      critical: true,
      tags: ["mysql"],
      rule: { kind: "pattern", regex: r`\bcreate\s+(database|schema)\s+(if\s+not\s+exists\s+)?[\x60"']?\w+` },
      failFeedback: "No CREATE DATABASE statement found.",
      suggestion: "Add `CREATE DATABASE student_portal;` to your SQL file.",
    },
    {
      id: "students-table",
      label: "students table structure (id, name, email, course)",
      level: 3,
      weight: 15,
      critical: true,
      tags: ["mysql"],
      rule: { kind: "sql_table", table: "students", columns: ["id", "name", "email", "course"] },
      failFeedback: "Required students table structure missing.",
      suggestion: "Create the students table with the columns id, name, email and course, then resubmit.",
    },
    {
      id: "php-page",
      label: "PHP page created",
      level: 1,
      weight: 10,
      critical: true,
      tags: ["php"],
      rule: { kind: "file_exists", pathPattern: r`\.php$`, contentFallback: r`<\?php` },
      failFeedback: "No PHP page was found in the submission.",
      suggestion: "Include your index.php (or paste its code, starting with `<?php`, in your report).",
    },
    {
      id: "php-db-connection",
      label: "PHP database connection detected",
      level: 3,
      weight: 15,
      critical: true,
      tags: ["php", "mysql"],
      rule: { kind: "pattern", regex: r`(new\s+mysqli\s*\(|mysqli_connect\s*\(|new\s+PDO\s*\(\s*["']mysql:)` },
      failFeedback: "The PHP code never connects to MySQL.",
      suggestion: "Use `new mysqli(...)` or `new PDO('mysql:host=localhost;dbname=student_portal', ...)`.",
    },
    {
      id: "students-query",
      label: "Students queried from the database",
      level: 3,
      weight: 5,
      tags: ["php", "mysql"],
      rule: { kind: "pattern", regex: r`\bselect\b[\s\S]{0,200}?\bfrom\s+[\x60"']?students\b` },
      failFeedback: "No SELECT query on the students table was found.",
      suggestion: "Query the table, e.g. `SELECT id, name, email, course FROM students`.",
    },
    {
      id: "students-rendered",
      label: "Student rows rendered on the page",
      level: 3,
      weight: 5,
      tags: ["php"],
      rule: { kind: "pattern", regex: r`(fetch_assoc|fetch_array|fetch_object|fetchAll|->fetch\s*\(|mysqli_fetch_\w+)` },
      failFeedback: "The query results are never fetched and displayed.",
      suggestion: "Loop over the results with `while ($row = $result->fetch_assoc())` and echo each student.",
    },
    {
      id: "apache-serving",
      label: "Application served through Apache",
      level: 2,
      weight: 10,
      tags: ["apache"],
      rule: {
        kind: "pattern",
        regex: r`(/var/www/html|DocumentRoot\s+\S+|curl\s+[^\n]*(localhost|127\.0\.0\.1)|https?://(localhost|127\.0\.0\.1))`,
      },
      failFeedback: "There is no evidence the page is deployed to Apache's web root or tested through Apache.",
      suggestion: "Copy index.php into /var/www/html and test it with `curl http://localhost/index.php`.",
    },
    {
      id: "no-root-db-user",
      label: "Application does not connect as MySQL root",
      level: 3,
      weight: 5,
      tags: ["security"],
      rule: { kind: "absent", regex: r`(mysqli_connect|new\s+mysqli|new\s+PDO)\s*\([^;]*["']root["']` },
      failFeedback: "The PHP code connects to the database as root.",
      suggestion: "Create a dedicated user: `CREATE USER 'portal_user'@'localhost' IDENTIFIED BY '...'; GRANT SELECT ON student_portal.* TO 'portal_user'@'localhost';`",
    },
  ],
  procedure: {
    minWords: 150,
    topics: [
      {
        id: "commands",
        label: "Commands used",
        patterns: [r`\b(apt(-get)?|dnf|yum)\s+install\b`, r`\bsudo\s+\w+`, r`\bsystemctl\s+\w+`],
        missingFeedback: "Your procedure does not list the commands you ran.",
      },
      {
        id: "apache-config",
        label: "Apache configuration",
        patterns: [r`\bapache2?\b[\s\S]{0,300}?\b(config|configured|configure|DocumentRoot|/var/www|a2ensite|virtual\s*host|httpd\.conf|sites-available)`, r`\bDocumentRoot\b`, r`/var/www/html`],
        missingFeedback: "Your implementation is correct, but your procedure does not explain how Apache was configured.",
      },
      {
        id: "database-commands",
        label: "Database commands",
        patterns: [r`\bcreate\s+(database|table)\b`, r`\binsert\s+into\b`],
        missingFeedback: "Your procedure does not show the database commands (CREATE DATABASE / CREATE TABLE / INSERT).",
      },
      {
        id: "php-implementation",
        label: "PHP implementation",
        patterns: [r`(mysqli|PDO|<\?php|index\.php)`],
        missingFeedback: "Your procedure does not explain the PHP implementation or how PHP connects to MySQL.",
      },
    ],
  },
};
