import type { MissionDefinition } from "@/types/mission";

const r = String.raw;

export const NC_001: MissionDefinition = {
  id: "NC-001",
  companyId: "nexacore",
  level: 2,
  title: "Production LAMP Deployment",
  client: "NexaCore Internal Platforms",
  difficulty: "Advanced",
  priority: "High",
  estimatedTime: "2–3 hours",
  deadline: "Go-live window · 3 h",
  brief: [
    "NexaCore's Employee Portal — a PHP application with user login — must go live on a fresh Linux server before the next release window.",
    "This is a production system: it needs its own Apache virtual host with logging, hardened PHP, a least-privilege database account, secure authentication, correct file permissions, a firewall, error handling and a backup strategy. Security will review every line of your submission.",
  ],
  objectives: [
    "Create a dedicated Apache virtual host (ServerName, DocumentRoot, ErrorLog, CustomLog) and enable it.",
    "Enable the Apache modules the app needs (rewrite, headers, ssl) and serve the site over HTTPS.",
    "Disable directory listing for the document root.",
    "Harden PHP for production (display_errors Off, sensible limits).",
    "Create the application database, a dedicated database user and grant only the privileges it needs.",
    "Create a `users` table with id, username (or email) and password_hash.",
    "Implement login with password_hash / password_verify, prepared statements and PHP sessions.",
    "Load database credentials from environment configuration — never hardcode them.",
    "Set Linux ownership and permissions for the web root (www-data).",
    "Configure the firewall to allow only SSH, HTTP and HTTPS.",
    "Add error handling (try/catch or an exception handler) and log errors instead of displaying them.",
    "Back up the database with mysqldump and schedule it (cron).",
  ],
  constraints: [
    "No `GRANT ALL PRIVILEGES ON *.*` — least privilege only.",
    "No database credentials hardcoded in PHP source.",
    "Passwords must never be stored in plain text.",
    "No hardcoded connections as the MySQL root user.",
    "Errors must not be displayed to end users in production.",
  ],
  expectedOutput: [
    "A .zip containing: the vhost .conf file, setup/deploy script (all commands), schema.sql (database, user, grants, users table), PHP source (config/db connection, login), php.ini overrides, backup script / cron entry.",
    "A single detailed .txt / .md / .pdf / .docx report containing all of the above is also accepted.",
    "Max file size: 4 MB.",
  ],
  hints: [
    "Virtual host skeleton: `<VirtualHost *:443> ServerName portal.nexacore.local DocumentRoot /var/www/nexacore/public ErrorLog ${APACHE_LOG_DIR}/nexacore_error.log CustomLog ${APACHE_LOG_DIR}/nexacore_access.log combined </VirtualHost>` then `a2ensite nexacore.conf`.",
    "Least privilege: `CREATE USER 'nexa_app'@'localhost' IDENTIFIED BY '...'; GRANT SELECT, INSERT, UPDATE ON nexacore.* TO 'nexa_app'@'localhost';`",
    "Credentials: `SetEnv DB_PASS ...` in the vhost (or a .env outside the web root) and `getenv('DB_PASS')` in PHP. Login: `$stmt = $pdo->prepare('SELECT * FROM users WHERE username = ?'); ... password_verify($input, $row['password_hash'])`.",
    "Ops: `ufw allow OpenSSH && ufw allow 'Apache Full' && ufw enable`, `chown -R www-data:www-data /var/www/nexacore`, `mysqldump nexacore > /backups/nexacore.sql` in a crontab.",
  ],
  submission: {
    allowedExtensions: [".zip", ".txt", ".md", ".pdf", ".docx", ".php", ".sql", ".sh", ".conf", ".ini"],
    maxSizeMB: 4,
  },
  passThreshold: 75,
  requirements: [
    {
      id: "vhost-file",
      label: "Apache virtual host configuration provided",
      level: 1,
      weight: 6,
      critical: true,
      tags: ["apache"],
      rule: { kind: "file_exists", pathPattern: r`\.conf$`, contentFallback: r`<VirtualHost\b` },
      failFeedback: "No Apache virtual host configuration was found.",
      suggestion: "Include your site's .conf file from /etc/apache2/sites-available/.",
    },
    {
      id: "vhost-servername",
      label: "Virtual host with ServerName and DocumentRoot",
      level: 3,
      weight: 8,
      critical: true,
      tags: ["apache"],
      rule: {
        kind: "pattern",
        regex: r`<VirtualHost\s+[^>]*:(80|443)\s*>[\s\S]*?\bServerName\s+\S+[\s\S]*?</VirtualHost>`,
      },
      failFeedback: "The virtual host is missing a ServerName (or is not a valid <VirtualHost *:80|443> block).",
      suggestion: "Define `<VirtualHost *:443>` with `ServerName`, `DocumentRoot` and close it with `</VirtualHost>`.",
    },
    {
      id: "apache-logging",
      label: "Apache error and access logging",
      level: 2,
      weight: 6,
      tags: ["apache", "logging"],
      rule: { kind: "keywords", mode: "all", keywords: ["ErrorLog", "CustomLog"] },
      failFeedback: "Dedicated ErrorLog / CustomLog directives are missing.",
      suggestion: "Add `ErrorLog ${APACHE_LOG_DIR}/nexacore_error.log` and `CustomLog ${APACHE_LOG_DIR}/nexacore_access.log combined`.",
    },
    {
      id: "apache-modules",
      label: "Apache modules enabled",
      level: 4,
      weight: 5,
      tags: ["apache"],
      rule: {
        kind: "commands",
        mode: "any",
        commands: [r`\ba2enmod\s+[^\n]*\b(rewrite|ssl|headers)\b`, r`\bLoadModule\s+(rewrite|ssl|headers)_module\b`],
      },
      failFeedback: "No Apache modules were enabled.",
      suggestion: "Enable what the app needs: `sudo a2enmod rewrite headers ssl`.",
    },
    {
      id: "site-enabled",
      label: "Site enabled with a2ensite",
      level: 4,
      weight: 4,
      tags: ["apache"],
      rule: { kind: "commands", mode: "any", commands: [r`\ba2ensite\s+\S+`] },
      failFeedback: "The new site was never enabled.",
      suggestion: "Run `sudo a2ensite nexacore.conf && sudo a2dissite 000-default.conf && sudo systemctl reload apache2`.",
    },
    {
      id: "https",
      label: "HTTPS configured",
      level: 3,
      weight: 5,
      tags: ["security", "networking"],
      rule: { kind: "pattern", regex: r`(\bSSLEngine\s+on\b|\bcertbot\b|<VirtualHost\s+[^>]*:443\s*>)` },
      failFeedback: "The site is not served over HTTPS.",
      suggestion: "Add a `<VirtualHost *:443>` with `SSLEngine on` and certificates (or use certbot).",
    },
    {
      id: "no-directory-listing",
      label: "Directory listing disabled",
      level: 2,
      weight: 3,
      tags: ["security", "apache"],
      rule: { kind: "pattern", regex: r`\bOptions\s+[^\n]*-Indexes\b` },
      failFeedback: "Directory listing is not disabled.",
      suggestion: "Inside your <Directory> block use `Options -Indexes +FollowSymLinks`.",
    },
    {
      id: "php-hardened",
      label: "PHP hardened (display_errors off)",
      level: 2,
      weight: 6,
      tags: ["php", "security"],
      rule: {
        kind: "pattern",
        regex: r`(display_errors\s*=\s*(off|0)\b|ini_set\s*\(\s*["']display_errors["']\s*,\s*["']?(0|off)|php_(admin_)?flag\s+display_errors\s+off)`,
      },
      failFeedback: "PHP still displays errors to users.",
      suggestion: "Set `display_errors = Off` and `log_errors = On` in php.ini (or `php_admin_flag display_errors off` in the vhost).",
    },
    {
      id: "env-config",
      label: "Credentials loaded from environment configuration",
      level: 3,
      weight: 8,
      critical: true,
      tags: ["security", "php"],
      rule: {
        kind: "pattern",
        regex: r`(\bgetenv\s*\(|\$_ENV\s*\[|\$_SERVER\s*\[\s*["']DB_|\bSetEnv\s+DB_|\bparse_ini_file\s*\(|\bDotenv\b)`,
      },
      failFeedback: "Database credentials are not loaded from environment configuration.",
      suggestion: "Use `getenv('DB_PASS')` with `SetEnv` in the vhost or a .env file outside the web root.",
    },
    {
      id: "no-root-db-user",
      label: "Application does not connect as MySQL root",
      level: 3,
      weight: 4,
      tags: ["security"],
      rule: { kind: "absent", regex: r`(mysqli_connect|new\s+mysqli|new\s+PDO)\s*\([^;]*["']root["']` },
      failFeedback: "The application connects to the database as root.",
      suggestion: "Connect with the dedicated application user you created.",
    },
    {
      id: "db-user",
      label: "Dedicated database user created",
      level: 3,
      weight: 6,
      critical: true,
      tags: ["mysql", "security"],
      rule: { kind: "pattern", regex: r`\bcreate\s+user\s+(if\s+not\s+exists\s+)?[\x60"']?\w+` },
      failFeedback: "No dedicated database user was created.",
      suggestion: "Add `CREATE USER 'nexa_app'@'localhost' IDENTIFIED BY '...';`.",
    },
    {
      id: "least-privilege",
      label: "Least-privilege GRANT on the app database",
      level: 3,
      weight: 6,
      tags: ["mysql", "security"],
      rule: {
        kind: "pattern",
        regex: r`\bgrant\s+(select|insert|update|delete)\b[\w\s,]*\bon\s+[\x60"']?\w+[\x60"']?\.\*`,
      },
      failFeedback: "Database privileges are not scoped to the application database.",
      suggestion: "Grant only what the app needs: `GRANT SELECT, INSERT, UPDATE ON nexacore.* TO 'nexa_app'@'localhost';`.",
    },
    {
      id: "no-grant-all",
      label: "No global GRANT ALL",
      level: 3,
      weight: 4,
      tags: ["mysql", "security"],
      rule: { kind: "absent", regex: r`\bgrant\s+all(\s+privileges)?\s+on\s+\*\.\*` },
      failFeedback: "The submission grants ALL PRIVILEGES on *.* — that violates least privilege.",
      suggestion: "Replace it with a GRANT scoped to the application database and only the required privileges.",
    },
    {
      id: "users-table",
      label: "users table (id, username/email, password_hash)",
      level: 3,
      weight: 6,
      critical: true,
      tags: ["mysql"],
      rule: { kind: "sql_table", table: "users", columns: ["id", ["username", "email"], ["password_hash", "password"]] },
      failFeedback: "Required users table structure missing.",
      suggestion: "Create `users` with id, username (or email) and password_hash columns.",
    },
    {
      id: "password-hashing",
      label: "Passwords hashed with password_hash / password_verify",
      level: 3,
      weight: 6,
      critical: true,
      tags: ["php", "security"],
      rule: { kind: "pattern", regex: r`\b(password_hash|password_verify)\s*\(` },
      failFeedback: "User authentication does not use password_hash / password_verify.",
      suggestion: "Store `password_hash($password, PASSWORD_DEFAULT)` and check with `password_verify()`.",
    },
    {
      id: "prepared-statements",
      label: "Prepared statements for user input",
      level: 3,
      weight: 6,
      tags: ["php", "security"],
      rule: { kind: "pattern", regex: r`(->prepare\s*\(|\bmysqli_prepare\s*\(|\bbind_param\s*\(|\bbindParam\s*\(|\bbindValue\s*\()` },
      failFeedback: "Queries do not use prepared statements — the login is open to SQL injection.",
      suggestion: "Use `$pdo->prepare('SELECT ... WHERE username = ?')` and `execute([$username])`.",
    },
    {
      id: "sessions",
      label: "PHP sessions for authenticated users",
      level: 3,
      weight: 3,
      tags: ["php"],
      rule: { kind: "pattern", regex: r`\bsession_start\s*\(` },
      failFeedback: "Logged-in state is not tracked with PHP sessions.",
      suggestion: "Call `session_start()` and store the user id in `$_SESSION` after a successful login.",
    },
    {
      id: "error-handling",
      label: "Error handling",
      level: 3,
      weight: 4,
      tags: ["php"],
      rule: {
        kind: "pattern",
        regex: r`(\btry\s*\{[\s\S]*?\bcatch\s*\(|\bset_exception_handler\s*\(|\bset_error_handler\s*\(|\bmysqli_report\s*\()`,
      },
      failFeedback: "No error handling was found in the PHP code.",
      suggestion: "Wrap the database connection in try/catch and log the exception with `error_log()`.",
    },
    {
      id: "file-permissions",
      label: "Linux ownership and permissions for the web root",
      level: 4,
      weight: 5,
      tags: ["linux", "security"],
      rule: {
        kind: "commands",
        mode: "any",
        commands: [r`\bchown\s+(-R\s+)?www-data`, r`\bchmod\s+(-R\s+)?[0-7]{3,4}\b`, r`\bfind\s+[^\n]*-type\s+[fd][^\n]*chmod`],
      },
      failFeedback: "Web root ownership/permissions were not set.",
      suggestion: "Run `sudo chown -R www-data:www-data /var/www/nexacore` and set 755 for directories / 644 for files.",
    },
    {
      id: "firewall",
      label: "Firewall configured",
      level: 4,
      weight: 5,
      tags: ["networking", "security"],
      rule: { kind: "commands", mode: "any", commands: [r`\bufw\s+(allow|enable)\b`, r`\bfirewall-cmd\s+`, r`\biptables\s+-A\b`] },
      failFeedback: "No firewall configuration was found.",
      suggestion: "Allow only what's needed: `sudo ufw allow OpenSSH && sudo ufw allow 'Apache Full' && sudo ufw enable`.",
    },
    {
      id: "db-backup",
      label: "Database backup",
      level: 4,
      weight: 5,
      tags: ["mysql", "ops"],
      rule: { kind: "commands", mode: "any", commands: [r`\bmysqldump\s+`, r`\bmariadb-dump\s+`] },
      failFeedback: "No database backup command was found.",
      suggestion: "Back up with `mysqldump nexacore > /var/backups/nexacore-$(date +%F).sql`.",
    },
    {
      id: "backup-schedule",
      label: "Backup scheduled",
      level: 4,
      weight: 3,
      tags: ["ops"],
      rule: { kind: "pattern", regex: r`(\bcrontab\b|/etc/cron\.|\bsystemd\s+timer\b|\.timer\b|^\s*[\d*/,-]+\s+[\d*/,-]+\s+[\d*/,-]+\s+[\d*/,-]+\s+[\d*/,-]+\s+\S+)`, flags: "im" },
      failFeedback: "The backup is not scheduled.",
      suggestion: "Add a cron entry, e.g. `0 2 * * * /usr/local/bin/backup-nexacore.sh`.",
    },
  ],
  procedure: {
    minWords: 300,
    topics: [
      {
        id: "commands",
        label: "Commands used",
        patterns: [r`\bsudo\s+\w+`, r`\bsystemctl\s+\w+`, r`\ba2(en|dis)(site|mod)\b`],
        missingFeedback: "Your procedure does not list the commands you ran.",
      },
      {
        id: "virtual-host",
        label: "Apache virtual host configuration",
        patterns: [r`virtual\s*host`, r`<VirtualHost`, r`\ba2ensite\b`, r`sites-available`],
        missingFeedback: "Your procedure does not explain how the Apache virtual host was configured.",
      },
      {
        id: "database-security",
        label: "Database user and permissions",
        patterns: [r`\bcreate\s+user\b`, r`\bgrant\b`, r`least[\s-]privilege`],
        missingFeedback: "Your procedure does not explain the database user and its permissions.",
      },
      {
        id: "authentication",
        label: "Authentication implementation",
        patterns: [r`\bpassword_(hash|verify)\b`, r`\bprepared\s+statements?\b`, r`\bsession_start\b`, r`\blogin\b`],
        missingFeedback: "Your procedure does not explain how user authentication was implemented.",
      },
      {
        id: "security-hardening",
        label: "Security hardening (firewall, permissions, PHP)",
        patterns: [r`\bufw\b`, r`\bfirewall\b`, r`\bchown\b`, r`\bchmod\b`, r`display_errors`],
        missingFeedback: "Your procedure does not cover security hardening (firewall, file permissions, PHP settings).",
      },
      {
        id: "backup",
        label: "Backup strategy",
        patterns: [r`\bmysqldump\b`, r`\bbackups?\b`, r`\bcron\b`],
        missingFeedback: "Your procedure does not describe the backup strategy.",
      },
    ],
  },
};
